### ISSUE TITLE
dragons often disapears and the plugin still thinks they are there.

### ISSUE THREAD

**Issue by CloudeLecaw** [EricLangezaal/PetDragon#13]
well on our servsr dragons that players left disapear may when chunk is unload or server is started?...
sell the problem is the database says they are there.
but they arent.
it would be nice if the database sees dragon is at Position x y z world then it should spawn the dragon if none is found anymore...

Server is 1.20.4 Paper
plugin Version - the latest

**Comment by EricLangezaal** [comment]
Ah that's unfortunately to hear. You are currently reporting this for the free version however, is that intentional? Since I know you have also purchased the Pro/Premium version.

**Comment by CloudeLecaw** [comment]
the free version? 
we are using the pro version..
so am i wrong here? My mistake. so please lead me to the right github <3

**Comment by EricLangezaal** [comment]
Yes I figured you would be using the pro version. The Pro version is not open source (so no public GitHub), but I will start a conversation about this issue on Spigot private message if that is okay? Basically if you could provide me with some additional details of when this happens exactly. I just checked and it definitely doesn't always happen when a chunk unloads, so if we can find the circumstances that cause this, that would be very helpful in fixing the bug. So please let me know any additional details in the Spigot thread. I am closing this thread as the free version does not actually have a database haha, so please respond on Spigot private conversation instead:)
