### ISSUE TITLE
Unable to compile.

### ISSUE THREAD

**Issue by andrewkm** [EricLangezaal/PetDragon#6]
Likely due to some new Spigot changes... (?)
https://pastebin.com/raw/G6Vc8ZLx

**Comment by EricLangezaal** [comment]
Nope, you are simply building against the wrong version of Java. Minecraft 1.17+ requires Java 16, you are using Java 11 it seems. Also, why exactly are you building this manually?

**Comment by andrewkm** [comment]
Ah wow, I was incredibly tired yesterday after a good 18 hour work day lol, can't believe I didn't notice the Java version being an issue.

@EricLangezaal We build all our plugins manually so our developers can make changes privately where we see fit for our environments.

**Comment by EricLangezaal** [comment]
Okay makes sense, good to hear the issue has been resolved.
