### ISSUE TITLE
Version v.1.19.3

### ISSUE THREAD

**Issue by vlladislav45** [EricLangezaal/PetDragon#9]
The lite version of the plugin does not support Spigot 1.19.3

**Comment by EricLangezaal** [comment]
Thank you for reminding me, will update it hopefully in the upcoming week. Just FYI the pro version is always updated at least a week earlier as a (paid) benefit, but kind of forgot the lite version this cycle.

**Comment by EricLangezaal** [comment]
Just [released](https://www.spigotmc.org/resources/82744/update?update=487617) the update! Don't forgot to leave a review:)

**Comment by vlladislav45** [comment]
@EricLangezaal of course i will rate you. <3
